name: Dr. Henry Naiken.Msc.D
favicon: null
layout_spectrum: 0.6421334501355886
typography_spectrum: 0.5809574245940894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8395824902690947
  lightness: 0.6079891454428434
  saturation: 0.9704977734945714
  rhythmicContrast: 0.9241850804537535
purpose: []
